variables:
  DOCKER_REGISTRY: 496965460335.dkr.ecr.eu-west-1.amazonaws.com
  APP_NAME: todo-app-api
  AWS_DEFAULT_REGION: eu-west-1
  DOCKER_HOST: tcp://docker:2375
  AWS_USERNAME: AWS

stages:
  - build-to-gitlab
  - test
  - build-to-aws-ecr


build-to-gitlab:
  stage: build-to-gitlab
  image: docker
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY_IMAGE:latest --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE:latest --build-arg="ENV=prod" --build-arg="BIND_ADDRESS=9090" .
    - docker push $CI_REGISTRY_IMAGE:latest

test:
  stage: test
  image: $CI_REGISTRY_IMAGE:latest
  script:
    - CGO_ENABLED=0 APP_ENV=prod go test -v ./...

build-to-aws-ecr:
  stage: build-to-aws-ecr
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
  script:
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:latest .
    - aws ecr get-login-password | docker login -u $AWS_USERNAME --password-stdin $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$APP_NAME:latest